name: CustomModelSwitcher
version: '1.0-SNAPSHOT'
main: org.github.rakletmole33.customModelSwitcher.Main
api-version: '1.21'

commands:
  cms:
    usage: /cms [number or itemname] [number or itemname]
    description: CustomModelDataを変更します！
    author: Rakletmole